apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: auth
      context: ./auth
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
      docker:
        dockerfile: Dockerfile
    - image: client 
      context: ./client
      sync:
        manual:
          - dest: .
            src: '**/*.js'
      docker:
        dockerfile: Dockerfile
    - image: tickets 
      context: ./tickets 
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
      docker:
        dockerfile: Dockerfile
    - image: orders 
      context: ./orders
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
      docker:
        dockerfile: Dockerfile

manifests:
  rawYaml:
    - ./infra/k8s/**/*
deploy:
  kubectl:
    defaultNamespace: "ticketing"