apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: auth
      context: ./auth
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
      docker:
        dockerfile: Dockerfile
    - image: client 
      context: ./client
      sync:
        manual:
          - dest: .
            src: '**/*.js'
      docker:
        dockerfile: Dockerfile
    - image: tickets 
      context: ./tickets 
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
      docker:
        dockerfile: Dockerfile
    - image: orders 
      context: ./orders
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
      docker:
        dockerfile: Dockerfile
    - image: expiration
      context: ./expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: payments 
      context: ./payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

profiles:
  - name: kustomize-local
    activation:
      - command: dev
    manifests:
      kustomize:
        paths:
          - infra/k8s/overlays/local
    deploy:
      kubectl: {}

  - name: legacy-raw
    manifests:
      rawYaml:
        - infra/k8s/deploys/*.k8s.yaml
        - infra/k8s/ingresses/*.k8s.yaml
    deploy:
      kubectl:
        defaultNamespace: "ticketing"
