server {
  listen 80;
  server_name _;

  location /api/users {
    proxy_pass http://auth:3000;
    proxy_http_version 1.1;
  }

  location /api/tickets {
    proxy_pass http://tickets:3000;
    proxy_http_version 1.1;
  }

  location /api/orders {
    proxy_pass http://orders:3000;
    proxy_http_version 1.1;
  }

  location /api/payments {
    proxy_pass http://payments:3000;
    proxy_http_version 1.1;
  }

  location / {
    return 404;
  }
}
