apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ticketing
resources:
  - ../../base
images:
  - name: docker.io/example/ticketing-auth
    newName: auth
    newTag: dev
  - name: docker.io/example/ticketing-client
    newName: client
    newTag: dev
  - name: docker.io/example/ticketing-expiration
    newName: expiration
    newTag: dev
  - name: docker.io/example/ticketing-orders
    newName: orders
    newTag: dev
  - name: docker.io/example/ticketing-payments
    newName: payments
    newTag: dev
  - name: docker.io/example/ticketing-tickets
    newName: tickets
    newTag: dev
replicas:
  - name: auth
    count: 1
  - name: client
    count: 1
  - name: expiration
    count: 1
  - name: orders
    count: 1
  - name: payments
    count: 1
  - name: tickets
    count: 1
  - name: nats-jets
    count: 1
  - name: auth-mongo
    count: 1
  - name: tickets-mongo
    count: 1
  - name: orders-mongo
    count: 1
  - name: payments-mongo
    count: 1
  - name: expiration-redis
    count: 1
patchesStrategicMerge:
  - local-pullpolicy.yaml
  - local-ingress.yaml
  - local-imagepullsecrets.yaml
  - local-expiration-probes.yaml
