apiVersion: apps/v1 
kind: Deployment
metadata:
  name: expiration-redis
spec:
  selector:
    matchLabels:
      app: expiration-redis
  template:
    metadata:
      labels:
        app: expiration-redis
    spec:
      containers:
        - name: expiration-redis
          image: redis:7.4-alpine3.21

---

apiVersion: v1
kind: Service
metadata:
  name: expiration-redis-svc
spec:
  selector:
    app: expiration-redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: db
    
    
  