apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      name: expiration
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: expiration 
          imagePullPolicy: Never
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'nats://nats-jets-svc:4222' 
            - name: NATS_CLUSTER_ID
              value: ticketing 
            - name: REDIS_HOST 
              value: expiration-redis-svc