apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      name: orders
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: orders 
          imagePullPolicy: Never
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'nats://nats-jets-svc:4222' 
            - name: NATS_CLUSTER_ID
              value: ticketing 
            - name: MONGO_URI
              value: mongodb://orders-mongo-svc:27017/orders
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY 
                  
---
apiVersion: v1
kind: Service
metadata:
  name: orders-svc
spec:
  selector:
    app: orders
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: orders