apiVersion: apps/v1 
kind: Deployment
metadata:
  name: tickets-mongo
spec:
  selector:
    matchLabels:
      app: tickets-mongo
  template:
    metadata:
      labels:
        app: tickets-mongo
    spec:
      containers:
        - name: tickets-mongo
          image: mongo:7.0.11-jammy

---

apiVersion: v1
kind: Service
metadata:
  name: tickets-mongo-svc
spec:
  selector:
    app: tickets-mongo
  ports:
    - port: 27017 
      targetPort: 27017
      protocol: TCP
      name: db