apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - auth.yaml
  - auth-mongo.yaml
  - client.yaml
  - expiration.yaml
  - expiration-redis.yaml
  - nats.yaml
  - orders.yaml
  - orders-mongo.yaml
  - payments.yaml
  - payments-mongo.yaml
  - tickets.yaml
  - tickets-mongo.yaml
  - ingress.yaml
commonLabels:
  app.kubernetes.io/part-of: ticketing
