name: Simple Deploy to Staging

on:
  push:
    branches: 
      - main

jobs:
  build-and-push-services:
    permissions:
      contents: read
      packages: write # Needed for GHCR
    name: Build and Push Services
    uses: ./.github/workflows/build-and-push-containers.yaml 